# Run the SDV python jupyter notebook (including installation of dependencies)

name: SDV CI

on: 
  push:
    paths:
      # only run when SDV folder contents are edited
      - 'methods/SDV/**'

jobs:
  run_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      # requires sdv and runipy (to run the notebook in command line)
      run: pip install sdv runipy
    - name: Run notebook
      # just run the notebook for now (testing will be added later)
      run: runipy methods/SDV/SDV_pipeline.ipynb
