# Run synthpop R script (including installing dependencies)
name: synthpop CI

on:
  push:
    paths:
      - 'methods/synthpop/**'
      - '.github/workflows/synthpop_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic

    steps:
    - uses: actions/checkout@v1
    - name: Install System Dependencies
      run: |
        sudo apt-get update && apt-get install -y --no-install-recommends \
        libxml2-dev \
        libssl-dev \
        libcurl4-openssl-dev
    - name: Run script
      run: Rscript methods/synthpop/synthpop_pipeline.R
