# Run synthpop R script (including installing dependencies)
name: synthpop CI

on:
  push:
    paths:
      - 'methods/synthpop/**'

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic

    steps:
    - uses: actions/checkout@v1
    - name: Install Package Dependencies
      run: Rscript -e "install.packages('synthpop')"
    - name: Run script
      run: Rscript methods/synthpop/synthpop_pipeline.R
